#include "QuokkaApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<QuokkaApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

QuokkaApp::QuokkaApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  QuokkaApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  QuokkaApp::associateSyntax(_syntax, _action_factory);
}

QuokkaApp::~QuokkaApp()
{
}

// External entry point for dynamic application loading
extern "C" void QuokkaApp__registerApps() { QuokkaApp::registerApps(); }
void
QuokkaApp::registerApps()
{
  registerApp(QuokkaApp);
}

// External entry point for dynamic object registration
extern "C" void QuokkaApp__registerObjects(Factory & factory) { QuokkaApp::registerObjects(factory); }
void
QuokkaApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void QuokkaApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { QuokkaApp::associateSyntax(syntax, action_factory); }
void
QuokkaApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
